// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sac_to_do_list;

#nullable disable

namespace sactodolist.Migrations
{
    [DbContext(typeof(AttivitaContext))]
    [Migration("20230111143456_rimossorelazione_cliente")]
    partial class rimossorelazionecliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttivitaDipendente", b =>
                {
                    b.Property<int>("AttivitàAttivitaId")
                        .HasColumnType("int");

                    b.Property<int>("DipendenteId")
                        .HasColumnType("int");

                    b.HasKey("AttivitàAttivitaId", "DipendenteId");

                    b.HasIndex("DipendenteId");

                    b.ToTable("AttivitaDipendente");
                });

            modelBuilder.Entity("sac_to_do_list.Account", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("sac_to_do_list.Attivita", b =>
                {
                    b.Property<int>("AttivitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttivitaId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stato")
                        .HasColumnType("bit");

                    b.HasKey("AttivitaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Attività");
                });

            modelBuilder.Entity("sac_to_do_list.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("CognomeUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("sac_to_do_list.Dipendente", b =>
                {
                    b.Property<int>("DipendenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DipendenteId"));

                    b.Property<string>("CognomeUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DipendenteId");

                    b.ToTable("Dipendenti");
                });

            modelBuilder.Entity("AttivitaDipendente", b =>
                {
                    b.HasOne("sac_to_do_list.Attivita", null)
                        .WithMany()
                        .HasForeignKey("AttivitàAttivitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sac_to_do_list.Dipendente", null)
                        .WithMany()
                        .HasForeignKey("DipendenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sac_to_do_list.Attivita", b =>
                {
                    b.HasOne("sac_to_do_list.Cliente", null)
                        .WithMany("Attivita")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("sac_to_do_list.Cliente", b =>
                {
                    b.Navigation("Attivita");
                });
#pragma warning restore 612, 618
        }
    }
}
